# Generated by Django 4.2.20 on 2025-03-27 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidateprofile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="candidateprofile",
            name="name",
        ),
        migrations.RemoveField(
            model_name="candidateprofile",
            name="resume_file",
        ),
        migrations.RemoveField(
            model_name="candidateprofile",
            name="user",
        ),
    ]
