# Generated by Django 4.2.20 on 2025-03-27 04:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("required_skills", models.JSONField(blank=True, null=True)),
                ("posted_date", models.DateTimeField(auto_now_add=True)),
                ("closing_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
